export const environment = {
  production: false,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MjcyODA0Yy04ZDBlLTRjNzktODIyMS0yNmJhNTk0MzVlMTYiLCJlbWFpbCI6IkJydW5vdmluaW1lbGxvUEBob3RtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJCcnVubyIsIm5iZiI6MTY5NzIxNTE1MSwiZXhwIjoxNjk3MjQzOTUxLCJpYXQiOjE2OTcyMTUxNTEsImlzcyI6ImVBZ2VuZGEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0In0.f6Yg4bKV_lN2Gd-NHU9T0qTpo2VCVFUYY3nV0aPMaqE'
}
